FROM mcr.microsoft.com/dotnet/core/sdk:3.1
WORKDIR /api
COPY . .
RUN dotnet publish -o /publish
WORKDIR /publish
# ENV ASPNETCORE_URLS http://localhost:80
ENTRYPOINT [ "dotnet","cv-custom-middleware.dll" ]